version: '3.3'
services:
    php-fpm:
        image: gpupo/container-orchestration:symfony-dev
        env_file:
            - .env
            - .env.local
        volumes:
            - $PWD/:/var/www/app
        networks:
            - backend
        links:
            - redis
            - mariadb
    mariadb:
        image: mariadb
        restart: always
        expose:
          - 3306
        environment:
          MYSQL_ROOT_PASSWORD: mas7er
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mariadb
        expose:
          - 80
        restart: always
        env_file:
            - Resources/phpmyadmin.env
        networks:
            - backend
            - default
    nginx-upstream:
        image: gpupo/container-orchestration:nginx-upstream
        env_file:
            - .env
            - .env.local
        expose:
            - 80
        links:
            - php-fpm
        volumes:
            - $PWD/:/var/www/app/
        networks:
            - default
            - backend
        environment:
            - PHP_SERVER=php-fpm
    redis:
        image: redis:alpine
        expose:
            - 6379
        networks:
            - backend
networks:
    default:
        external:
            name: nginx-proxy
    backend:
