version: '3.3'
services:
    php-fpm:
        image: gpupo/container-orchestration:symfony-dev-${TAG_VERSION}
        env_file:
            - .env
            - .env.local
        volumes:
            - $PWD/:/var/www/app
        networks:
            - backend
        links:
            - mariadb
        ports:
            - 3000:3000
    mariadb:
        image: mariadb
        restart: always
        expose:
          - 3306
        environment:
          MYSQL_ROOT_PASSWORD: mas7er
        networks:
            - backend
    nginx-upstream:
        image: gpupo/container-orchestration:nginx-upstream
        env_file:
            - .env
            - .env.local
        expose:
            - 80
        links:
            - php-fpm
        volumes:
            - $PWD/:/var/www/app/
        networks:
            - default
            - backend
        environment:
            - PHP_SERVER=php-fpm
networks:
    default:
        external:
            name: nginx-proxy
    backend:
