repository: gpupo-meta/dockerized-helloworld
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-sitemap
