version: '3.3'
services:
    jekyll:
        image: starefossen/github-pages
        env_file:
            - .env
        volumes:
            - $PWD/:/usr/src/app
        ports:
            - 4000:4000
